#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then change the shebang line to that shell.
#
#   (2) The slurp flag will cause gradle to fail if multiple gradle installs are
#       in your PATH. There should only be one gradle installation in PATH,
#       and it should be the one of the version written in .java-version file.
#       If there is more than one gradle installation in PATH, please remove
#       the extra ones.
#
#   (3) This script is generated by the Gradle wrapper (by requesting the Gradle
#       distribution). The end of this Gradle script will try to load a newer
#       version of Gradle if the .java-version file indicates that is the case
#       immediately.
#
#   (4) The Gradle wrapper only uses java to start and to stop a Daemon. All the
#       actual magic is done by Gradle.
#
#   How to manually remove the Gradle wrapper files from your project:
#   - For .gradle-wrapper directory on each Gradle version use "rm -rf" command:
#   - delete the gradle wrapper jar file: rm gradle/wrapper/gradle-wrapper.jar
#   - delete the gradle wrapper properties file: rm gradle/wrapper/gradle-wrapper.properties
#
##############################################################################

exec "$JAVACMD" \
  "-Dorg.gradle.appname=$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
